package de.spacemate.orchestration;

/**
 * Every meaningful state transition that the UI needs to react to.
 */
public enum OnboardingEventType {
    CUSTOMER_REGISTERED,
    QUESTIONNAIRE_SENT,
    QUESTIONNAIRE_COMPLETED,
    INDEMNITY_SENT,
    INDEMNITY_SIGNED,
    APPOINTMENT_SUGGESTED,
    APPOINTMENT_SENT,
    APPOINTMENT_CONFIRMED,
    APPOINTMENT_CANCELLED,
    APPOINTMENT_COMPLETED,
    APPOINTMENT_TIMESLOT_REFUSED,
    APPOINTMENT_TYPE_REFUSED,
    STEP_SKIPPED,
    MEDICAL_RESULT_RECORDED,
    CUSTOMER_APPROVED,
    CUSTOMER_REJECTED,
    APPOINTMENT_REFUSED,
    SIMULATE_RESULT,
    STAGE_CHANGED
}
