package de.spacemate.model;

public enum DocumentCategory {
    QUESTIONNAIRE,
    AI_LEGAL_REPORT,
    AI_MEDICAL_REPORT,
    AI_TRAINER_REPORT,
    MEDICAL_REPORT,
    SPECIALIST_REPORT,
    TRAINING_REPORT,
    APPOINTMENT_PROPOSAL,
    APPOINTMENT_RESPONSE,
    INDEMNITY_AGREEMENT,
    INDEMNITY_RESPONSE
}
