package de.spacemate.model;

public enum OnboardingStage {
    REGISTERED,
    QUESTIONNAIRE_SENT,
    QUESTIONNAIRE_COMPLETED,
    INDEMNITY_PENDING,
    INDEMNITY_SIGNED,
    FIRST_MEDICAL_SCHEDULED,
    FIRST_MEDICAL_COMPLETED,
    SPECIALIST_SCHEDULED,
    SPECIALIST_COMPLETED,
    SPACE_TRAINING_SCHEDULED,
    SPACE_TRAINING_COMPLETED,
    FINAL_MEDICAL_SCHEDULED,
    FINAL_MEDICAL_COMPLETED,
    APPROVED,
    REJECTED,
    FAILED,
    APPOINTMENT_REFUSED
}
